# =============================================================================
# BEHAVE CONFIGURATION
# =============================================================================
# FILE: .behaverc, behave.ini
#
# SEE ALSO:
#  * https://github.com/behave/behave
#  * https://behave.readthedocs.io/en/latest/behave/#configuration-files
# =============================================================================

[behave]
default_format = pretty
default_tags = not (@xfail or @not_implemented)
stdout_capture = false
show_source = true
