# =============================================================================
# READTHEDOCS CONFIG-FILE: .readthedocs.yaml
# =============================================================================
# SEE ALSO:
#  * https://docs.readthedocs.io/en/stable/config-file/v2.html
#  * https://blog.readthedocs.com/migrate-configuration-v2/
# =============================================================================

version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

python:
  install:
    - requirements: py.requirements/docs.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  builder: dirhtml
  fail_on_warning: true

# -- PREPARED: Additional formats to generate
formats:
  - pdf
