# =============================================================================
# CI-SERVER CONFIGURATION: behave
# =============================================================================
# OS: Windows
# SEE ALSO:
#   * http://www.appveyor.com/docs/build-configuration
#   * http://www.appveyor.com/docs/installed-software#python
#   * http://www.appveyor.com/docs/appveyor-yml
#
# VALIDATE: appveyor.yml
#   * https://ci.appveyor.com/tools/validate-yaml
# =============================================================================
# https://bootstrap.pypa.io/get-pip.py

version: 1.2.6.dev0.{build}-{branch}
clone_folder: C:\projects\behave.ci
# clone_depth:  2
# shallow_clone: true

environment:
  PYTHONPATH: ".;%CD%"
  BEHAVE_ROOTDIR_PREFIX: "C:"
  matrix:
    - PYTHON_DIR:  C:\Python36-x64
      PYTHON: C:\Python36-x64\python.exe
    - PYTHON_DIR:  C:\Python27-x64
      PYTHON: C:\Python27-x64\python.exe
      BEHAVE_ROOTDIR_PREFIX: "c:"

# -- TEMPORARILY DISABLED: environment matrix:
#    - PYTHON_DIR:  C:\Python35-x64
#      PYTHON: C:\Python35-x64\python.exe
#    - PYTHON_DIR:  C:\Python35
#      PYTHON: C:\Python35\python.exe

# -- TEMPORARILY DISABLED: environment matrix:
#    - PYTHON_DIR:  C:\Python36
#    - PYTHON_DIR:  C:\Python27-x64
#    - PYTHON_DIR:  C:\Python36-x64

init:
    - cmd: "echo TESTING-WITH %PYTHON_DIR%, %PYTHON%"
    - cmd: "%PYTHON_DIR%\\python.exe --version"
    - cmd: "%PYTHON% --version"
    - cmd: "echo CD=%CD%"
    - cmd: "echo PYTHONPATH=%PYTHONPATH%"
    - cmd: set

# -- TEMPORARILY DISABLED: Python variants discovery
#    - cmd: "@echo AVAILABLE PYTHON VERSIONS"
#    - cmd: "@dir C:\Python*"
#    - path

install:
    - cmd: "%PYTHON_DIR%\\python.exe -m pip install pytest mock PyHamcrest nose"
    - cmd: "%PYTHON_DIR%\\python.exe -m pip install ."
    - cmd: "%PYTHON_DIR%\\python.exe bin/explore_platform_encoding.py"

# NOT-NEEDED:   - cmd: "%PYTHON_DIR%\\python.exe -m pip install parse"

build: off
test_script:
    - cmd: "%PYTHON_DIR%\\Scripts\\pytest.exe test tests"
    - cmd: "%PYTHON_DIR%\\Scripts\\behave.exe -f progress3 --junit features"
    - cmd: "%PYTHON_DIR%\\Scripts\\behave.exe -f progress3 --junit issue.features"
