# -- TEST-VARIANT: pypy-27 on ubuntu-latest
# BASED ON: tests.yml
# SPECIAL CASE:
#   - CAN NOT USE: pip install -e .
#   - MUST USE: python -mbehave ... -- Script seems not to be created.

name: test-pypy27
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release/**" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"
  pull_request:
    types: [opened, reopened, review_requested]
    branches: [ "main" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    # -- DISABLED: continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["pypy-2.7"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'py.requirements/*.txt'

      - name: Install Python package dependencies (step 0)
        run: |
          python -m pip install -U pip setuptools build wheel
          pip --version
      - name: Install Python package dependencies (step 1)
        run: |
           pip install -r py.requirements/ci.github.testing.txt
           pip list
      - name: Install Python package dependencies (step 2)
        run: |
           pip install .
      - name: Run tests
        run: pytest
      - name: "Run behave tests: features ..."
        run: python -mbehave --format=progress3 features
      - name: "Run behave tests: issue.features ..."
        run: python -mbehave --format=progress3 issue.features
      - name: "Run behave tests: tools/test-features ..."
        run: python -mbehave --format=progress3 tools/test-features
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test reports
          path: |
            build/testing/report.xml
            build/testing/report.html
            # MAYBE: build/behave.reports/
        if: ${{ job.status == 'failure' }}
        # MAYBE: if: ${{ always() }}
