# -- FAST-PROTOTYPING: Tests on Windows -- Until tests are OK.
# BASED ON: tests.yml
# SUPPORTED PYTHON VERSIONS: https://github.com/actions/python-versions

name: test-windows
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release/**" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"
  pull_request:
    types: [opened, reopened, review_requested]
    branches: [ "main" ]
    paths:
      - ".github/**/*.yml"
      - "**/*.py"
      - "**/*.feature"
      - "py.requirements/**"
      - "*.cfg"
      - "*.ini"
      - "*.toml"


# -- TEST BALLOON: Fix encoding="cp1252" problems by using "UTF-8"
env:
  PYTHONUTF8: 1

jobs:
  test:
    # DISABLED: runs-on: ${{ matrix.os }}
    runs-on: "windows-latest"
    # -- PREPARED: continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        # DISABLED: os: ["windows-latest"]
        python-version: ["3.13", "3.12", "3.11", "3.10"]
        # -- PREPARED FOR: Experimental Python versions with "continue-on-error".
        # experimental: [false]
        # include:
        #  - python-version: "3.13"
        #    experimental: true
    steps:
      - uses: actions/checkout@v5
      # DISABLED: name: Setup Python ${{ matrix.python-version }} on platform=${{ matrix.os }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # DISABLED: cache: 'pip'
          # DISABLED: cache-dependency-path: 'py.requirements/*.txt'
      # -- DISABLED:
      # - name: Show Python version
      #   run: python --version
      - name: setup-uv -- Speed-up Python package installations ...
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/py.requirements/ci.github.testing.txt
            **/py.requirements/basic.txt
            **/py.requirements/testing.txt
      - name: "Install Python package dependencies (with: uv)"
        run: |
          uv pip install --system -U pip setuptools wheel
          uv pip install --system -U -r py.requirements/ci.github.testing.txt
          uv pip install --system -e .

      - name: Run tests
        run: pytest
      - name: "Run behave tests: features ..."
        run: behave --format=progress3 features
      - name: "Run behave tests: issue.features ..."
        run: behave --format=progress3 issue.features
      - name: "Run behave tests: tools/test-features ..."
        run: behave --format=progress3 tools/test-features
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test reports
          path: |
            build/testing/report.xml
            build/testing/report.html
            # MAYBE: build/behave.reports/
        if: ${{ job.status == 'failure' }}
        # MAYBE: if: ${{ always() }}
#      - name: Upload behave test reports
#        uses: actions/upload-artifact@v4
#        with:
#          name: behave.reports
#          path: build/behave.reports/
